module.exports = {
  tableName: "leave",
  columnNames: {
    id: "uuid",
    name: "name",
    date: "date",
    type: "type",
    dateFrom: "date_from",
    dateTo: "date_to",
    clockout: "clock_out",
    duration: "duration",
    vacationCount: "vacation_count",
    sickCount: "sick_count",
    reason: "reason",
    leaveForm: "leave_form",
    status: "status",
    userId: "user_id",
    createdAt: "created_at",
    updatedAt: "updated_at",
  },
};
