module.exports = {
  tableName: "leave",
  columnNames: {
    id: "uuid",
    name: "name",
    date: "date",
    leaveType: "leave_type",
    dayType: "day_type",
    dateFrom: "date_from",
    dateTo: "date_to",
    dateApproved: "date_approved",
    dateRejected: "date_rejected",
    clockout: "clock_out",
    duration: "duration",
    vlBalance: "vl_balance",
    slBalance: "sl_balance",
    reason: "reason",
    status: "status",
    decision: "decision",
    remarks: "remarks",
    userId: "user_id",
    createdAt: "created_at",
    updatedAt: "updated_at",
  },
};
